name: CI

on: [push]

jobs:
  build-release:
    name: Build Windows Release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download DirectX SDK
      run: |
        powershell.exe Invoke-WebRequest https://download.skyrim-together.com/DXSDK.zip -OutFile DXSDK.zip
        Expand-Archive -Path DXSDK.zip -DestinationPath DXSDK
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
  
    - name: Generate solution
      run: |
        cd Build
        ./MakeVS2019Projects.bat

    - name: Build Solution (windows)
      env: 
        DXSDK_DIR: $HOME/DXSDK
      run: |
        cd Build/projects
        MSBuild.exe "Tilted Online Framework.sln" -m -property:Configuration=Release
        
    - name: Upload Skyrim Artifacts
      uses: actions/upload-artifact@v2.2.0
      with:
        name: skyrim-artifacts
        path: |
          Build/bin/x64/tp_process.exe
          Build/bin/x64/Loader.exe
          Build/bin/x64/Proxy.dll
          Build/bin/x64/SkyrimTogether.dll
          Build/bin/x64/SkyrimTogetherServer.exe

    - name: Upload Fallout4 Artifacts
      uses: actions/upload-artifact@v2.2.0
      with:
        name: fallout4-artifacts
        path: |
          Build/bin/x64/tp_process.exe
          Build/bin/x64/Loader.exe
          Build/bin/x64/Proxy.dll
          Build/bin/x64/FalloutTogether.dll
          Build/bin/x64/FalloutTogetherServer.exe
  
  build-debug:
    name: Build Windows Debug
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download DirectX SDK
      run: |
        powershell.exe Invoke-WebRequest https://download.skyrim-together.com/DXSDK.zip -OutFile DXSDK.zip
        Expand-Archive -Path DXSDK.zip -DestinationPath DXSDK
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
  
    - name: Generate solution
      run: |
        cd Build
        ./MakeVS2019Projects.bat

    - name: Build Solution (windows)
      env: 
        DXSDK_DIR: $HOME/DXSDK
      run: |
        cd Build/projects
        MSBuild.exe "Tilted Online Framework.sln" -m -property:Configuration=Debug
