name: CI

on: [push]

jobs:
  build:
    name: build-windows-release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download DirectX SDK
      run: |
        powershell.exe Invoke-WebRequest https://download.skyrim-together.com/DXSDK.zip -OutFile DXSDK.zip
        Expand-Archive -Path DXSDK.zip -DestinationPath DXSDK
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
  
    - name: Generate solution
      run: |
        cd Build
        ./MakeVS2019Projects.bat

    - name: Build Solution (windows)
      run: |
        cd Build/projects
        MSBuild.exe "Tilted Online Framework.sln"
